---
layout: post
title:  "Coba Install Arch Linux"
date:   2022-05-04 08:01:54 +0700
categories: 
---

# Bootable Windows 10 Dari Linux Pake WoeUSB

biar GUI ya ges yak.

# pake git dulu, sumber clone => https://aur.archlinux.org/packages/woeusb

# kalo uda diclone, masuk ke-dir

~: cd woeusb

# lalu build pkgnya

~: makepkg -si

# output :

==> Making package: woeusb 5.2.4-1 (Wed 04 May 2022 07:51:18 AM WIB)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading woeusb-5.2.4.bash...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 76373  100 76373    0     0  39250      0  0:00:01  0:00:01 --:--:--  309k
==> Validating source files with sha256sums...
    woeusb-5.2.4.bash ... Passed
==> Extracting sources...
==> Starting prepare()...
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "woeusb"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: woeusb 5.2.4-1 (Wed 04 May 2022 07:51:21 AM WIB)
==> Installing package woeusb with pacman -U...
loading packages...
warning: woeusb-5.2.4-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) woeusb-5.2.4-1

Total Installed Size:  0.07 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
:: Processing package changes...
(1/1) reinstalling woeusb                          [######################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...


# tinggal install kek pake rufus. sekian.
